import { useEffect, useState } from "react";
import { streamApi } from "../lib/api";

type Props={status:string;score:number;explanation:string;blockerCount:number;changeSetCount:number;fingerprint:string};

export default function ReadinessRumiExplanation({status,score,explanation,blockerCount,changeSetCount,fingerprint}:Props){
 const[content,setContent]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 useEffect(()=>{let active=true;setContent("");setError("");setLoading(true);const prompt=`Explain this AGATA readiness decision for the user. Use only these supplied facts and do not invent anything. Current readiness: ${status} at ${score}%. Deterministic explanation: ${explanation}. Blockers: ${blockerCount}. Available change actions: ${changeSetCount}. Decision fingerprint: ${fingerprint}. Explain why the decision exists, what the decision means operationally, and how the user should interpret the available change actions. Clearly state that AGATA's deterministic readiness engine remains the source of truth and Rumi is only explaining the result.`;void streamApi("/api/rumi/chat",{messages:[{role:"user",content:prompt}]},token=>{if(active)setContent(current=>current+token)}).catch(err=>{if(active)setError(err instanceof Error?err.message:"Rumi could not explain this decision.")}).finally(()=>{if(active)setLoading(false)});return()=>{active=false}},[status,score,explanation,blockerCount,changeSetCount,fingerprint]);
 return <section className="rumi-decision-explanation"><div className="rumi-decision-head"><div><span>RUMI · EXPLANATION LAYER</span><h3>What this decision means</h3></div><b>RUMI</b></div>{error?<div className="rumi-decision-error">{error}</div>:<p>{loading&&!content?"Rumi is explaining the deterministic decision…":content}</p>}<footer>Rumi explains the deterministic readiness result; it cannot override the readiness engine.</footer><style>{`.rumi-decision-explanation{margin-top:12px;border:1px solid #28445b;border-radius:12px;background:#07131e;padding:14px}.rumi-decision-head{display:flex;justify-content:space-between;gap:12px;align-items:flex-start}.rumi-decision-head span{color:#718ca5;font-size:8px;font-weight:750;letter-spacing:.16em}.rumi-decision-head h3{margin:6px 0 0;font-size:15px}.rumi-decision-head b{border:1px solid #35526a;border-radius:999px;padding:5px 7px;color:#8fb2c9;font-size:8px}.rumi-decision-explanation p{margin:10px 0;color:#a4b7c7;font-size:9px;line-height:1.65;white-space:pre-wrap}.rumi-decision-error{margin-top:10px;color:#df9ca5;font-size:9px}.rumi-decision-explanation footer{border-top:1px solid #162b3d;padding-top:9px;color:#5f778d;font-size:8px}`}</style></section>;
}
