import { useEffect, useState } from "react";
import { api } from "../lib/api";

type Event={id:string;action:string;entity_type:string;entity_id:string|null;description:string;actor:string;created_at:string};
const css=`.audit-page{max-width:1180px;margin:0 auto;padding:32px;color:#eef2f7}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d}.muted{color:#8792a3}.filters{display:grid;grid-template-columns:1.4fr 1fr 1fr auto;gap:10px;margin-top:22px}.filters input,.filters select{background:#0d1016;color:#fff;border:1px solid rgba(255,255,255,.1);padding:11px;border-radius:10px}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;margin-top:16px}.event{padding:18px 20px;border-bottom:1px solid rgba(255,255,255,.06)}.top{display:flex;justify-content:space-between;gap:18px}.meta{font-size:12px;color:#7f8a9a;margin-top:7px}.empty{padding:38px;text-align:center}@media(max-width:800px){.filters{grid-template-columns:1fr 1fr}.top{flex-direction:column;gap:5px}}
`;
export default function AuditPage(){const [events,setEvents]=useState<Event[]>([]);const [search,setSearch]=useState("");const [type,setType]=useState("");const [action,setAction]=useState("");const [error,setError]=useState("");
 const load=()=>{const q=new URLSearchParams();if(search)q.set("search",search);if(type)q.set("entity_type",type);if(action)q.set("action",action);api<Event[]>(`/api/audit?${q}`).then(setEvents).catch(e=>setError(e instanceof Error?e.message:"Unable to load audit trail."));};useEffect(()=>{load()},[type,action]);
 return <main className="audit-page"><style>{css}</style><p className="eyebrow">GOVERNANCE</p><h1>Audit Trail</h1><p className="muted">Trace important changes and compliance decisions across the workspace.</p><div className="filters"><input placeholder="Search event descriptions…" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&load()}/><select value={type} onChange={e=>setType(e.target.value)}><option value="">All entities</option><option value="readiness">Readiness</option><option value="document">Evidence</option><option value="project">Project</option><option value="contractor">Contractor</option><option value="requirement">Requirement</option></select><select value={action} onChange={e=>setAction(e.target.value)}><option value="">All actions</option><option value="created">Created</option><option value="updated">Updated</option><option value="evaluated">Evaluated</option><option value="deleted">Deleted</option></select><button onClick={load} style={{border:0,borderRadius:10,padding:"0 16px",fontWeight:700}}>Filter</button></div>{error&&<div className="panel" style={{padding:16}}>{error}</div>}<section className="panel">{events.map(e=><div className="event" key={e.id}><div className="top"><strong>{e.description}</strong><span className="meta">{new Date(e.created_at).toLocaleString()}</span></div><div className="meta">{e.actor} · {e.entity_type}{e.entity_id?` · ${e.entity_id}`:""} · {e.action}</div></div>)}{!events.length&&!error&&<div className="empty"><strong>No matching audit events</strong><p className="muted">As workspace activity occurs, AGATA will record traceable events here.</p></div>}</section></main>}
