import { useEffect, useState } from "react";
import { api } from "../lib/api";

const css=`.billing-page{max-width:1180px;margin:0 auto;padding:32px;color:#eef2f7}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d}.muted{color:#8792a3}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end}.hero h1{margin:8px 0}.grid{display:grid;grid-template-columns:1.2fr .8fr;gap:18px;margin-top:24px}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:22px}.plan{border:1px solid rgba(120,145,255,.35);background:linear-gradient(145deg,#0d111b,#090b0f);border-radius:16px;padding:24px}.price{font-size:34px;font-weight:800;margin:10px 0}.pill{display:inline-flex;padding:6px 9px;border-radius:99px;background:#151a23;font-size:11px;letter-spacing:1px;text-transform:uppercase}.row{display:flex;justify-content:space-between;gap:20px;padding:14px 0;border-top:1px solid rgba(255,255,255,.06)}.bar{height:8px;background:#171b22;border-radius:99px;overflow:hidden}.bar i{display:block;height:100%;background:#7187ff}@media(max-width:800px){.grid{grid-template-columns:1fr}.hero{align-items:flex-start;flex-direction:column}}
`;
export default function BillingPage(){
 const [summary,setSummary]=useState<any>(null);const [error,setError]=useState("");
 useEffect(()=>{api<any>("/api/workspace/summary").then(setSummary).catch(e=>setError(e instanceof Error?e.message:"Unable to load billing information."));},[]);
 const counts=summary?.counts;const total=(counts?.projects||0)+(counts?.contractors||0)+(counts?.requirements||0)+(counts?.evidence||0);const cap=100;
 return <main className="billing-page"><style>{css}</style><header className="hero"><div><p className="eyebrow">COMMERCIAL CONTROL</p><h1>Billing &amp; Plan</h1><p className="muted">A transparent view of workspace plan state and current scale. Payment processing is deliberately not simulated.</p></div></header>{error&&<div className="panel" style={{marginTop:18}}>{error}</div>}<div className="grid"><section><article className="plan"><span className="pill">Development workspace</span><h2>AGATA Foundation</h2><p className="muted">Core project, contractor, requirement, evidence, readiness and intelligence workflows.</p><div className="price">Active</div><div className="muted">No payment method or recurring charge is connected to this workspace.</div></article><article className="panel" style={{marginTop:18}}><p className="eyebrow">WHAT'S INCLUDED</p>{["Project and contractor workflows","Evidence and requirement mapping","Readiness decisions","Rumi intelligence","Notifications and audit trail","Workspace analytics"].map(x=><div className="row" key={x}><span>{x}</span><strong>Included</strong></div>)}</article></section><aside className="panel"><p className="eyebrow">WORKSPACE SCALE</p><h2>{summary?.company?.name||"AGATA Workspace"}</h2><div className="row"><span>Projects</span><strong>{counts?.projects??0}</strong></div><div className="row"><span>Contractors</span><strong>{counts?.contractors??0}</strong></div><div className="row"><span>Requirements</span><strong>{counts?.requirements??0}</strong></div><div className="row"><span>Evidence</span><strong>{counts?.evidence??0}</strong></div><div style={{marginTop:18}}><div className="row" style={{border:0}}><span>Recorded resources</span><strong>{total}</strong></div><div className="bar"><i style={{width:`${Math.min(100,total/cap*100)}%`}}/></div><p className="muted" style={{fontSize:12}}>This is an operational scale indicator, not a billing charge or usage limit.</p></div></aside></div></main>;
}
