import { useEffect, useState } from "react";
import { api } from "../lib/api";

const css=`.billing-page{max-width:1220px;margin:0 auto;padding:32px;color:#eef2f7}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d;font-weight:700}.muted{color:#8792a3;line-height:1.55}.hero{display:flex;justify-content:space-between;gap:20px;align-items:end}.hero h1{margin:8px 0 6px;font-size:30px}.grid{display:grid;grid-template-columns:1.35fr .65fr;gap:18px;margin-top:26px}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:24px}.plan{border:1px solid rgba(120,145,255,.3);background:linear-gradient(145deg,#0d111b,#090b0f);border-radius:16px;padding:26px}.plan-top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.plan h2{margin:8px 0}.pill,.badge{display:inline-flex;padding:6px 9px;border-radius:99px;background:#151a23;color:#aeb9c9;font-size:10px;letter-spacing:1px;text-transform:uppercase;font-weight:750}.state{font-size:13px;color:#aeb9c9}.section{margin-top:18px}.row{display:flex;justify-content:space-between;gap:20px;padding:15px 0;border-top:1px solid rgba(255,255,255,.06)}.row:first-child{border-top:0}.metric{font-size:24px;font-weight:800}.action{margin-top:20px;background:#e8edf5;color:#07090d;border:0;border-radius:10px;padding:11px 16px;font-weight:750;cursor:pointer}.action:disabled{opacity:.45;cursor:not-allowed}.bar{height:7px;background:#171b22;border-radius:99px;overflow:hidden;margin-top:9px}.bar i{display:block;height:100%;background:#7187ff}.note{padding:13px 14px;border-radius:11px;background:#0d1016;border:1px solid rgba(255,255,255,.06);font-size:12px;color:#9aa6b7;margin-top:18px}.provider{display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-top:14px}.provider button{padding:12px;border:1px solid rgba(255,255,255,.08);background:#0d1016;color:#dbe2ec;border-radius:10px;cursor:pointer}.provider button.active{border-color:#7187ff;background:#121829}.provider-state{font-size:11px;margin-top:7px}.ready{color:#7ee2a8}.not-ready{color:#e8a4a4}.quota{display:grid;grid-template-columns:1fr 1fr;gap:10px;margin-top:18px}.quota-card{padding:14px;border:1px solid rgba(255,255,255,.06);border-radius:12px;background:#0d1016}.quota-card strong{display:block;font-size:18px;margin-top:5px}.table{width:100%;border-collapse:collapse;font-size:12px}.table th,.table td{text-align:left;padding:12px 8px;border-top:1px solid rgba(255,255,255,.06)}@media(max-width:800px){.grid{grid-template-columns:1fr}.hero{align-items:flex-start;flex-direction:column}.provider{grid-template-columns:1fr}.quota{grid-template-columns:1fr}}
`;

type Plan={code:string;name:string;description:string;currency:string;amount_minor:number;interval:string;active:boolean;provider_ready?:Record<string,boolean>};
type Payment={id:string;provider:string;amount_minor:number;currency:string;status:string;paid_at:string|null;created_at:string};
type Billing={provider:string;subscriptions:Array<{id:string;provider:string;plan:Plan;status:string;current_period_start:string|null;current_period_end:string|null;cancel_at_period_end:boolean}>;payments:Payment[]};
type Summary={company?:{name:string};counts?:{projects:number;contractors:number;requirements:number;evidence:number;users:number}};
type Entitlements={plan:{code:string;name:string;interval:string};limits:Record<string,number>;usage:Record<string,number>;remaining:Record<string,number>;at_limit:Record<string,boolean>};

export default function BillingPage(){
 const [billing,setBilling]=useState<Billing|null>(null);const [plans,setPlans]=useState<Plan[]>([]);const [summary,setSummary]=useState<Summary|null>(null);const [entitlements,setEntitlements]=useState<Entitlements|null>(null);const [provider,setProvider]=useState("paystack");const [error,setError]=useState("");const [checkoutMessage,setCheckoutMessage]=useState("");const [loading,setLoading]=useState(false);
 const load=()=>Promise.all([api<Billing>("/api/billing"),api<Plan[]>("/api/billing/plans"),api<Summary>("/api/workspace/summary"),api<Entitlements>("/api/billing/entitlements")]).then(([b,p,s,e])=>{setBilling(b);setPlans(p);setProvider(b.provider);setSummary(s);setEntitlements(e)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load billing information."));
 useEffect(()=>{
  const params=new URLSearchParams(window.location.search);const checkout=params.get("checkout");const reference=params.get("reference");
  if(checkout==="success"&&reference){
   setLoading(true);setError("");setCheckoutMessage("Verifying your Paystack payment…");
   api<{verified:boolean;plan:{name:string};subscription_status:string}>(`/api/billing/paystack/verify/${encodeURIComponent(reference)}`)
    .then(result=>setCheckoutMessage(`${result.plan.name} payment verified. Your subscription is now active.`))
    .catch(e=>setError(e instanceof Error?e.message:"Unable to verify the Paystack payment."))
    .finally(()=>{window.history.replaceState({},document.title,window.location.pathname);load().finally(()=>setLoading(false));});
  } else {load();}
 },[]);
 const paidPlans=plans.filter(p=>p.amount_minor>0);
 const startCheckout=async(plan:Plan)=>{setLoading(true);setError("");setCheckoutMessage("");try{const result=await api<{authorization_url:string}>("/api/billing/checkout",{method:"POST",body:JSON.stringify({plan_code:plan.code,provider})});window.location.assign(result.authorization_url)}catch(e){setError(e instanceof Error?e.message:"Unable to start checkout.")}finally{setLoading(false)}};
 const counts=summary?.counts;const resources=(counts?.projects||0)+(counts?.contractors||0)+(counts?.requirements||0)+(counts?.evidence||0);const providerReady=paidPlans.some(p=>p.provider_ready?.[provider]);
 return <main className="billing-page"><style>{css}</style>
  <header className="hero"><div><p className="eyebrow">COMMERCIAL CONTROL</p><h1>Billing &amp; Plan</h1><p className="muted">Subscription, usage and payment administration for this AGATA workspace.</p></div><span className="badge">Billing engine ready</span></header>
  {checkoutMessage&&<div className="panel" style={{marginTop:18}}>{checkoutMessage}</div>}
  {error&&<div className="panel" style={{marginTop:18}}>{error}</div>}
  <div className="grid"><section>
   <article className="plan"><div className="plan-top"><div><span className="pill">Current billing</span><h2>{billing?.subscriptions[0]?.plan.name||"AGATA Foundation"}</h2><p className="muted">Provider-independent subscriptions with Paystack, Stripe and Flutterwave adapters.</p></div><div className="state">{billing?.subscriptions[0]?.status||"No paid subscription"}</div></div>
    <div className="provider">{(["paystack","stripe","flutterwave"] as const).map(p=><button key={p} className={provider===p?"active":""} onClick={()=>setProvider(p)}>{p[0].toUpperCase()+p.slice(1)}<div className={`provider-state ${paidPlans.some(x=>x.provider_ready?.[p])?"ready":"not-ready"}`}>{paidPlans.some(x=>x.provider_ready?.[p])?"Checkout configured":"Plan ID required"}</div></button>)}</div>
    <div className="note">{providerReady?`The selected provider (${provider}) has a configured recurring plan and can accept checkout requests.`:`The selected provider (${provider}) has credentials available, but its recurring plan ID is not configured yet. Checkout will remain safely disabled until the provider plan is mapped.`}</div>
    {paidPlans.length===0?<div className="note">No paid plans are available. Run the billing migration to seed AGATA pricing.</div>:paidPlans.map(plan=><div className="row" key={plan.code}><div><strong>{plan.name}</strong><div className="muted">{plan.description}</div></div><div><strong>{(plan.amount_minor/100).toFixed(2)} {plan.currency}</strong><div className="muted">per {plan.interval}</div><button className="action" disabled={loading||!plan.provider_ready?.[provider]} onClick={()=>startCheckout(plan)}>{plan.provider_ready?.[provider]?"Continue to checkout":"Provider setup required"}</button></div></div>)}
    {entitlements&&<div className="quota">{(["users","projects","contractors","evidence"] as const).map(key=><div className="quota-card" key={key}><span className="eyebrow">{key}</span><strong>{entitlements.usage[key]} / {entitlements.limits[key]}</strong><span className="muted">{entitlements.remaining[key]} remaining</span></div>)}</div>}
   </article>
   <article className="panel section"><p className="eyebrow">PAYMENT HISTORY</p>{billing?.payments.length?<table className="table"><thead><tr><th>Provider</th><th>Amount</th><th>Status</th><th>Date</th></tr></thead><tbody>{billing.payments.map(p=><tr key={p.id}><td>{p.provider}</td><td>{(p.amount_minor/100).toFixed(2)} {p.currency}</td><td>{p.status}</td><td>{new Date(p.paid_at||p.created_at).toLocaleDateString()}</td></tr>)}</tbody></table>:<p className="muted">No payments recorded yet.</p>}</article>
  </section>
  <aside className="panel"><p className="eyebrow">WORKSPACE USAGE</p><h2>{summary?.company?.name||"AGATA Workspace"}</h2><p className="muted">Operational scale only. These figures are live workspace counts, not fabricated quotas.</p><div className="row"><span>Projects</span><strong>{counts?.projects??0}</strong></div><div className="row"><span>Contractors</span><strong>{counts?.contractors??0}</strong></div><div className="row"><span>Requirements</span><strong>{counts?.requirements??0}</strong></div><div className="row"><span>Evidence</span><strong>{counts?.evidence??0}</strong></div><div className="row"><span>Team members</span><strong>{counts?.users??0}</strong></div><div className="section"><span className="eyebrow">RECORDED RESOURCES</span><div className="metric">{resources}</div><div className="bar"><i style={{width:`${Math.min(100,resources)}%`}}/></div></div></aside></div>
 </main>;
}
