import { useEffect, useMemo, useState } from "react";
import { useNavigate } from "react-router-dom";
import { api } from "../lib/api";

type NotificationItem={id:string;kind:string;severity:"critical"|"warning"|"info";title:string;description:string;href:string;status:"active"|"resolved";read_at:string|null;created_at:string};
type Filter="all"|"unread"|"critical"|"warning"|"info"|"resolved";
export default function NotificationsPage(){const navigate=useNavigate();const[items,setItems]=useState<NotificationItem[]>([]);const[filter,setFilter]=useState<Filter>("all");const[query,setQuery]=useState("");const[loading,setLoading]=useState(true);const[error,setError]=useState("");
 async function load(){try{setLoading(true);setError("");setItems(await api<NotificationItem[]>("/api/notifications?status=all"));}catch(e){setError(e instanceof Error?e.message:"Unable to load notifications.");}finally{setLoading(false)}} useEffect(()=>{void load()},[]);
 const counts=useMemo(()=>({all:items.filter(x=>x.status==="active").length,unread:items.filter(x=>x.status==="active"&&!x.read_at).length,critical:items.filter(x=>x.status==="active"&&x.severity==="critical").length,warning:items.filter(x=>x.status==="active"&&x.severity==="warning").length,info:items.filter(x=>x.status==="active"&&x.severity==="info").length,resolved:items.filter(x=>x.status==="resolved").length}),[items]);
 const filtered=useMemo(()=>{const q=query.trim().toLowerCase();return items.filter(x=>{if(filter==="resolved"?x.status!=="resolved":x.status!=="active")return false;if(filter==="unread"&&x.read_at)return false;if(["critical","warning","info"].includes(filter)&&x.severity!==filter)return false;return !q||`${x.title} ${x.description} ${x.kind}`.toLowerCase().includes(q)})},[items,filter,query]);
 async function read(id:string){try{const updated=await api<NotificationItem>(`/api/notifications/${id}/read`,{method:"PATCH"});setItems(x=>x.map(i=>i.id===id?updated:i))}catch(e){setError(e instanceof Error?e.message:"Unable to update notification.")}}
 async function readAll(){try{await api("/api/notifications/read-all",{method:"POST"});const now=new Date().toISOString();setItems(x=>x.map(i=>i.status==="active"?{...i,read_at:i.read_at??now}:i))}catch(e){setError(e instanceof Error?e.message:"Unable to update notifications.")}}
 return <section style={{maxWidth:1180,margin:"0 auto",padding:"34px 0",color:"#e8eef8"}}><header style={{display:"flex",justifyContent:"space-between",gap:20,marginBottom:22}}><div><small style={{letterSpacing:".15em",color:"#73839a",fontWeight:800}}>ADMIN · NOTIFICATIONS</small><h1 style={{margin:"7px 0"}}>Notifications</h1><p style={{color:"#8392a7"}}>Live evidence and readiness signals requiring attention.</p></div>{counts.unread>0&&<button style={button} onClick={()=>void readAll()}>Mark all read</button>}</header>{error&&<div style={errorBox}>{error}</div>}<div style={stats}>{[["Needs attention",counts.all],["Unread",counts.unread],["Critical",counts.critical],["Warnings",counts.warning]].map(([l,v])=><div style={stat} key={String(l)}><small>{l}</small><strong>{v}</strong></div>)}</div><div style={toolbar}><input style={input} value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search notifications"/>{(["all","unread","critical","warning","info","resolved"] as Filter[]).map(v=><button key={v} style={{...tab,...(filter===v?activeTab:{})}} onClick={()=>setFilter(v)}>{v.replace("_"," ")} <span>{counts[v]}</span></button>)}</div><div style={panel}>{loading?<div style={empty}>Checking your workspace…</div>:filtered.length===0?<div style={empty}>No notifications match this view.</div>:filtered.map(i=><article style={row} key={i.id}><div style={{width:8,height:8,borderRadius:"50%",marginTop:7,background:i.severity==="critical"?"#ff7f8b":i.severity==="warning"?"#e4b46b":"#77b5ed"}}/><div style={{flex:1}}><small style={{color:"#718198",textTransform:"uppercase"}}>{i.severity} · {i.status}</small><h3 style={{margin:"5px 0"}}>{i.title}</h3><p style={{margin:0,color:"#7e8da2",fontSize:12}}>{i.description}</p><div style={{marginTop:10,display:"flex",gap:8}}>{i.status==="active"&&!i.read_at&&<button style={button} onClick={()=>void read(i.id)}>Mark read</button>}<button style={button} onClick={()=>navigate(i.href)}>Open {i.kind.startsWith("readiness")?"readiness":"evidence"} →</button></div></div></article>)}</div></section>}
const button={border:"1px solid #24364c",background:"#101b29",color:"#c5d5e6",borderRadius:8,padding:"8px 11px",fontSize:11,fontWeight:700,cursor:"pointer"} as const;const errorBox={padding:12,marginBottom:14,border:"1px solid #5a2930",borderRadius:9,color:"#ffb9c0",background:"#21171b",fontSize:12} as const;const stats={display:"grid",gridTemplateColumns:"repeat(4,1fr)",gap:12,marginBottom:16} as const;const stat={padding:16,border:"1px solid #1d2b3d",borderRadius:13,background:"#0d1722"} as const;const toolbar={display:"flex",gap:6,flexWrap:"wrap",marginBottom:12} as const;const input={flex:"1 1 240px",background:"#0c141f",border:"1px solid #1c2a3b",borderRadius:9,padding:"10px 12px",color:"#e8eef8"} as const;const tab={...button,background:"transparent",color:"#718198"} as const;const activeTab={background:"#152235",color:"#dce8f7"} as const;const panel={background:"#0b131e",border:"1px solid #1b293a",borderRadius:15,overflow:"hidden"} as const;const row={display:"flex",gap:14,padding:19,borderBottom:"1px solid #152231"} as const;const empty={minHeight:230,display:"grid",placeItems:"center",color:"#73839a"} as const;
