import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../lib/api";
import ReadinessDecisionReplay from "../components/ReadinessDecisionReplay";

type Item={id:string;created_at:string;score:number;status:string;explanation:string;requirement_count:number;evidence_count:number;blocker_count:number;change_set_count:number;score_delta:number|null;status_changed:boolean;blockers_added:string[];blockers_resolved:string[];fingerprint:string};
type Timeline={count:number;items:Item[];project_id:string;contractor_id:string};
type Replay={state:{score:number;status:string;explanation:string;requirements:Array<{requirement_name?:string}>;evidence:Array<{name?:string}>;blockers:Array<{requirement_name?:string}>;change_set:Array<{label?:string}>};captured_at:string;engine_version:string;fingerprint:string};
const label=(v:string)=>v.replaceAll("_"," ").replace(/\b\w/g,c=>c.toUpperCase());
const rumiPrompt=(item:Item,replay:Replay)=>{const blockers=replay.state.blockers.map(v=>v.requirement_name).filter(Boolean);const changes=replay.state.change_set.map(v=>v.label).filter(Boolean);const evidence=replay.state.evidence.map(v=>v.name).filter(Boolean);return `Explain this AGATA readiness decision trace using the supplied historical trace as the authoritative facts for this explanation. Do not invent or infer evidence validity, expiry, verification state, requirement details, or other facts that are not present in these supplied facts. Captured at: ${new Date(replay.captured_at).toLocaleString()}. Engine: ${replay.engine_version}. Status: ${label(replay.state.status)}. Score: ${replay.state.score}%. Deterministic explanation: ${replay.state.explanation}. Requirements captured: ${replay.state.requirements.length}. Evidence records captured: ${evidence.length}${evidence.length?` (${evidence.join(", ")})`:""}. Blockers captured: ${blockers.length}${blockers.length?` (${blockers.join(", ")})`:""}. Change actions captured: ${changes.length}${changes.length?` (${changes.join(", ")})`:""}. Decision fingerprint: ${replay.fingerprint}. Explain why this decision is in this state and what the decision-maker should understand. You may explain the operational meaning of the supplied blockers and change actions, but do not claim unsupported evidence conditions. Do not override the deterministic readiness result.`};

export default function ReadinessDecisionHistoryPage(){
 const{projectId,contractorId}=useParams();const navigate=useNavigate();const[data,setData]=useState<Timeline|null>(null);const[error,setError]=useState("");const[loading,setLoading]=useState(true);const[selectedTraceId,setSelectedTraceId]=useState<string|null>(null);const[rumiLoading,setRumiLoading]=useState(false);
 async function load(){if(!projectId||!contractorId)return;try{setLoading(true);setError("");setData(await api<Timeline>(`/api/readiness/projects/${projectId}/contractors/${contractorId}/timeline`));}catch(e){setError(e instanceof Error?e.message:"Unable to load decision history.")}finally{setLoading(false)}}
 useEffect(()=>{void load()},[projectId,contractorId]);
 async function askRumi(item?:Item){if(!projectId||!contractorId||rumiLoading)return;const target=item??data?.items[0];if(!target)return;try{setRumiLoading(true);setError("");const replay=await api<Replay>(`/api/readiness/projects/${projectId}/contractors/${contractorId}/replay/${target.id}`);navigate(`/rumi?prompt=${encodeURIComponent(rumiPrompt(target,replay))}`);}catch(e){setError(e instanceof Error?e.message:"Unable to prepare the decision context for Rumi.")}finally{setRumiLoading(false)}}
 if(loading)return <main className="history-page"><div className="state">Loading Decision History…</div></main>;
 if(!data)return <main className="history-page"><div className="error">{error||"Decision history unavailable."}</div></main>;
 const current=data.items[0];
 return <><style>{styles}</style><main className="history-page"><button className="back" onClick={()=>navigate(`/projects/${projectId}/contractors/${contractorId}`)}>← Back to Decision</button><header><div><span>READINESS · DECISION HISTORY</span><h1>How the readiness state changed</h1><p>Fingerprint-backed readiness states captured from the live workspace.</p></div><div className="count">{data.count} captured state{data.count===1?"":"s"}</div></header>{error&&<div className="error">{error}</div>}{current&&<div className="history-tools"><button onClick={()=>setSelectedTraceId(current.id)}>Replay current state →</button><button onClick={()=>void askRumi()} disabled={rumiLoading}>{rumiLoading?"Preparing Rumi…":"Ask Rumi to explain →"}</button></div>}<section className="timeline">{data.items.length===0?<div className="empty">No readiness states have been captured yet.</div>:data.items.map((item,index)=><article className={`item ${index===0?"current":""}`} key={item.id}><div className="rail"><i/>{index<data.items.length-1&&<b/>}</div><div className="record"><div className="top"><div><small>{new Date(item.created_at).toLocaleString()}</small><strong>{label(item.status)}</strong></div><em>{item.score}%</em></div><p>{item.explanation}</p><div className="metrics"><span>{item.requirement_count} requirements</span><span>{item.evidence_count} evidence</span><span>{item.blocker_count} blockers</span><span>{item.change_set_count} change actions</span>{item.score_delta!==null&&<span>{item.score_delta>=0?"+":""}{item.score_delta} pts</span>}</div>{(item.blockers_added.length||item.blockers_resolved.length)>0&&<div className="changes">{item.blockers_added.length>0&&<span className="added">New blockers: {item.blockers_added.join(", ")}</span>}{item.blockers_resolved.length>0&&<span className="resolved">Resolved: {item.blockers_resolved.join(", ")}</span>}</div>}<footer><span>Decision trace</span><code>{item.fingerprint}</code><button onClick={()=>setSelectedTraceId(selectedTraceId===item.id?null:item.id)}>{selectedTraceId===item.id?"Close replay":"Replay state"}</button><button onClick={()=>void askRumi(item)} disabled={rumiLoading}>{rumiLoading?"Preparing…":"Rumi"}</button></footer>{selectedTraceId===item.id&&projectId&&contractorId&&<ReadinessDecisionReplay projectId={projectId} contractorId={contractorId} traceId={item.id}/>}</div></article>)}</section></main></>;
}
const styles=`.history-page{max-width:1050px;margin:0 auto;padding:36px 30px 60px;color:#e7eef6}.back{border:0;background:none;color:#7792aa;font:600 11px inherit;cursor:pointer;margin-bottom:22px}.history-page header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.history-page header span{color:#718ca5;font-size:9px;font-weight:700;letter-spacing:.18em}.history-page h1{margin:8px 0;font-size:38px;letter-spacing:-.04em}.history-page header p{color:#71869b;font-size:11px}.count{border:1px solid #24415a;border-radius:999px;padding:8px 11px;color:#8eacc3;font-size:9px;white-space:nowrap}.history-tools{display:flex;gap:8px;margin-top:18px}.history-tools button,.record footer button{border:1px solid #29435a;background:#0a1723;color:#91aac0;border-radius:8px;padding:8px 10px;font:650 9px inherit;cursor:pointer}.history-tools button:first-child{border-color:#2b5f47;color:#78d4a0}.history-tools button:last-child{border-color:#35516a;color:#9bc3df}.history-tools button:disabled,.record footer button:disabled{opacity:.5;cursor:not-allowed}.error{margin:12px 0;padding:10px;border:1px solid #613740;background:#241419;color:#e2a0a8;border-radius:9px;font-size:10px}.timeline{margin-top:22px}.item{display:grid;grid-template-columns:30px 1fr;gap:12px;min-height:155px}.rail{position:relative;display:flex;justify-content:center}.rail i{width:10px;height:10px;margin-top:20px;border:2px solid #3a5e7c;border-radius:50%;background:#07111b;z-index:1}.current .rail i{border-color:#71d4a0;background:#0c2a1d}.rail b{position:absolute;top:31px;bottom:0;width:1px;background:#20364a}.record{border:1px solid #162b3d;border-radius:12px;background:#07111b;padding:14px;margin-bottom:9px}.current .record{border-color:#29465e;background:#081622}.top{display:flex;justify-content:space-between;gap:15px}.top small{display:block;color:#5d7890;font-size:8px;margin-bottom:5px}.top strong{font-size:12px}.top em{font-style:normal;font-size:18px;font-weight:750;color:#b8cfe0}.record>p{margin:9px 0;color:#70879c;font-size:9px;line-height:1.5}.metrics{display:flex;flex-wrap:wrap;gap:7px}.metrics span{border:1px solid #1b3348;background:#081723;color:#66839b;border-radius:999px;padding:4px 7px;font-size:8px}.changes{display:flex;flex-wrap:wrap;gap:9px;margin-top:9px;font-size:8px}.added{color:#d58c95}.resolved{color:#72d3a0}.record footer{display:flex;gap:9px;align-items:center;margin-top:10px;padding-top:9px;border-top:1px solid #14283a;color:#536e86;font-size:8px;flex-wrap:wrap}.record footer code{color:#6b88a1;overflow:hidden;text-overflow:ellipsis;white-space:nowrap;flex:1}.empty,.state{min-height:280px;display:grid;place-items:center;color:#70869b;font-size:11px}@media(max-width:700px){.history-page{padding:28px 18px}.history-page header{flex-direction:column}.item{grid-template-columns:20px 1fr}.history-tools{flex-wrap:wrap}.record footer code{width:100%;flex-basis:100%}}`;