import { useEffect, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { api } from "../lib/api";

type Decision = { id: string; status: "pending" | "approved" | "rejected"; decided_at: string | null; reason: string | null };
type ReadinessItem = { project_id: string; contractor_id: string; score: number | null; status: string | null; explanation: string | null; missing_requirements: string[] };
type Intelligence = { project_name: string; contractor_name: string; score: number; status: string; explanation: string };
const label = (value: string | null) => value ? value.replaceAll("_", " ").replace(/\b\w/g, c => c.toUpperCase()) : "Not evaluated";

export default function ReadinessDecisionOverviewPage() {
  const { projectId, contractorId } = useParams(); const navigate = useNavigate();
  const [decision, setDecision] = useState<Decision | null>(null); const [readiness, setReadiness] = useState<ReadinessItem | null>(null); const [intelligence, setIntelligence] = useState<Intelligence | null>(null); const [reason, setReason] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);
  async function load() { if (!projectId || !contractorId) return; try { setError(""); const [d, list, i] = await Promise.all([api<Decision>(`/api/readiness/projects/${projectId}/contractors/${contractorId}/decision`), api<ReadinessItem[]>("/api/readiness"), api<Intelligence>(`/api/readiness/projects/${projectId}/contractors/${contractorId}/intelligence`)]); setDecision(d); setReadiness(list.find(x => x.project_id === projectId && x.contractor_id === contractorId) ?? null); setIntelligence(i); } catch (err) { setError(err instanceof Error ? err.message : "Unable to load the readiness decision."); } }
  useEffect(() => { void load(); }, [projectId, contractorId]);
  async function decide(status: Decision["status"]) { if (!projectId || !contractorId) return; if (status === "rejected" && reason.trim().length < 3) { setError("Enter a rejection reason first."); return; } try { setSaving(true); setError(""); await api(`/api/readiness/projects/${projectId}/contractors/${contractorId}/decision`, { method: "POST", body: JSON.stringify({ status, reason: status === "rejected" ? reason.trim() : null }) }); setReason(""); await load(); } catch (err) { setError(err instanceof Error ? err.message : "Unable to update the decision."); } finally { setSaving(false); } }
  if (!decision || !readiness || !intelligence) return <main className="decision-overview"><div className="state">{error || "Loading readiness decision…"}</div></main>;
  const ready = readiness.status === "ready";
  return <><style>{styles}</style><main className="decision-overview"><button className="back" onClick={() => navigate("/readiness")}>← Back to Readiness</button><header><div><span>READINESS · DECISION</span><h1>{intelligence.project_name}</h1><p>{intelligence.contractor_name} · Review the current readiness result and choose where to go next.</p></div></header>{error && <div className="error">{error}</div>}<section className="summary-grid"><article className="card verdict"><span>READINESS</span><strong className={ready ? "ready" : "blocked"}>{label(readiness.status)}</strong><b>{readiness.score ?? 0}%</b><p>{readiness.explanation || intelligence.explanation}</p>{readiness.missing_requirements.length > 0 && <div className="attention"><small>BLOCKERS</small>{readiness.missing_requirements.slice(0, 5).map(item => <div key={item}>• {item}</div>)}</div>}</article><article className="card decision"><span>ORGANIZATIONAL DECISION</span><strong>{label(decision.status)}</strong>{decision.reason && <p>{decision.reason}</p>}{decision.decided_at && <small>Recorded {new Date(decision.decided_at).toLocaleString()}</small>}<div className="actions"><button disabled={saving || !ready} onClick={() => void decide("approved")}>Approve readiness</button><button disabled={saving || decision.status === "pending"} onClick={() => void decide("pending")}>Return to pending</button></div><textarea value={reason} onChange={e => setReason(e.target.value)} placeholder="Reason for rejection…"/><button className="reject" disabled={saving || !reason.trim()} onClick={() => void decide("rejected")}>Reject decision</button></article></section><section className="navigation-grid"><button onClick={() => navigate(`/projects/${projectId}/contractors/${contractorId}/decision/lens`)}><span>01 · DECISION LENS</span><strong>Why is this contractor in this state?</strong><p>Inspect blockers, evidence impact, minimum changes and preview proposed fixes.</p><i>Open Decision Lens →</i></button><button onClick={() => navigate(`/projects/${projectId}/contractors/${contractorId}/decision/history`)}><span>02 · DECISION HISTORY</span><strong>How did the readiness state change?</strong><p>Review captured readiness states, score movement and blocker changes.</p><i>Open Decision History →</i></button><button onClick={() => navigate("/rumi")}><span>03 · RUMI EXPLANATION</span><strong>Need the decision explained?</strong><p>Open Rumi for a dedicated explanation and guidance layer without changing the deterministic result.</p><i>Ask Rumi →</i></button></section><footer>Deterministic readiness is the source of truth. Rumi explains the result but cannot override the readiness engine.</footer></main></>;
}
const styles = `.decision-overview{max-width:1100px;margin:0 auto;padding:36px 30px 60px;color:#e7eef6}.back{border:0;background:none;color:#7792aa;font:600 11px inherit;cursor:pointer;margin-bottom:22px}.decision-overview header{display:flex;justify-content:space-between;gap:20px;align-items:flex-start}.decision-overview header span,.card>span,.navigation-grid span{color:#718ca5;font-size:9px;font-weight:700;letter-spacing:.18em}.decision-overview h1{margin:8px 0 0;font-size:36px;letter-spacing:-.04em}.decision-overview header p{color:#71869b;font-size:11px}.error{margin:12px 0;padding:10px;border:1px solid #613740;background:#241419;color:#e2a0a8;border-radius:9px;font-size:10px}.summary-grid,.navigation-grid{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:20px}.card,.navigation-grid>button{border:1px solid #1b3044;border-radius:15px;background:#060d15;padding:22px}.verdict strong{display:block;margin:18px 0 6px;font-size:25px}.verdict strong.ready{color:#70d69e}.verdict strong.blocked{color:#e1c16b}.verdict b{font-size:34px}.card p{color:#657d94;font-size:10px;line-height:1.55}.attention{border-top:1px solid #182a3b;margin-top:16px;padding-top:12px;color:#c7a65c;font-size:9px;line-height:1.6}.attention small{display:block;color:#71869b;margin-bottom:5px;letter-spacing:.12em}.decision>strong{display:block;margin:18px 0;color:#c9d8e5;font-size:22px}.decision small{color:#5e758b;font-size:8px}.actions{display:flex;gap:8px;margin:18px 0}.actions button,.reject{border:1px solid #29435a;background:#0a1723;color:#91aac0;border-radius:8px;padding:9px 11px;font:650 9px inherit;cursor:pointer}.actions button:first-child{border-color:#2a6948;background:#0b2418;color:#76d49d}.actions button:disabled,.reject:disabled{opacity:.4;cursor:not-allowed}.decision textarea{width:100%;box-sizing:border-box;min-height:65px;background:#07111b;border:1px solid #1e3449;border-radius:8px;color:#dce6ef;padding:9px;font:500 10px inherit;resize:vertical}.reject{margin-top:7px;border-color:#64383f;background:#25151a;color:#dd929b}.navigation-grid{margin-top:14px}.navigation-grid>button{text-align:left;color:#dce6ef;cursor:pointer;transition:.15s}.navigation-grid>button:hover{border-color:#3c6384;background:#091a29;transform:translateY(-1px)}.navigation-grid span{display:block;color:#607b94}.navigation-grid strong{display:block;margin:10px 0 6px;font-size:17px}.navigation-grid p{margin:0;color:#657d94;font-size:10px;line-height:1.5}.navigation-grid i{display:block;margin-top:17px;color:#8fb4d0;font-style:normal;font-size:9px;font-weight:700}.decision-overview footer{margin-top:14px;border:1px solid #172b3d;border-radius:11px;background:#07111b;padding:12px;color:#647c93;font-size:9px}.state{min-height:320px;display:grid;place-items:center;color:#70869b;font-size:11px}@media(max-width:760px){.summary-grid,.navigation-grid{grid-template-columns:1fr}.decision-overview{padding:28px 18px}.decision-overview header{flex-direction:column}}`;
