import { useEffect, useState } from "react";
import { api } from "../lib/api";

const css=`.settings-page{max-width:1180px;margin:0 auto;padding:32px;color:#eef2f7}.settings-head h1{margin:8px 0}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d}.muted{color:#8792a3}.settings-layout{display:grid;grid-template-columns:210px 1fr;gap:18px;margin-top:26px}.tabs{display:grid;align-content:start;gap:5px}.tab{background:transparent;border:1px solid transparent;color:#9aa6b7;text-align:left;padding:12px;border-radius:10px;cursor:pointer}.tab.active{background:#0b0e13;border-color:rgba(255,255,255,.08);color:#fff}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;padding:22px;margin-bottom:14px}.field{display:grid;gap:7px;margin-top:16px}.field label{font-size:12px;color:#aab4c3}.field input{background:#0d1016;color:#fff;border:1px solid rgba(255,255,255,.1);padding:11px;border-radius:10px}.save{margin-top:18px;background:#e8edf5;color:#07090d;border:0;border-radius:10px;padding:11px 16px;font-weight:750;cursor:pointer}.switch{display:flex;justify-content:space-between;gap:20px;padding:16px 0;border-top:1px solid rgba(255,255,255,.06)}@media(max-width:760px){.settings-layout{grid-template-columns:1fr}.tabs{display:flex;overflow:auto}}
`;
export default function SettingsPage(){
 const [data,setData]=useState<any>(null); const [name,setName]=useState(""); const [tab,setTab]=useState("workspace"); const [saved,setSaved]=useState(""); const [error,setError]=useState("");
 useEffect(()=>{api<any>("/api/workspace/profile").then(d=>{setData(d);setName(d.company?.name||"")}).catch(e=>setError(e instanceof Error?e.message:"Unable to load settings."));},[]);
 const save=()=>{localStorage.setItem("agata.settings.name",name);setSaved("Saved locally for this development workspace.");setTimeout(()=>setSaved(""),2500)};
 return <main className="settings-page"><style>{css}</style><header className="settings-head"><p className="eyebrow">WORKSPACE CONTROL</p><h1>Settings</h1><p className="muted">Workspace configuration, account preferences and intelligence controls.</p></header>{error&&<div className="panel">{error}</div>}<div className="settings-layout"><nav className="tabs">{[["workspace","Workspace"],["account","Account"],["notifications","Notifications"],["intelligence","Intelligence"],["security","Security"]].map(([id,label])=><button key={id} className={`tab ${tab===id?"active":""}`} onClick={()=>setTab(id)}>{label}</button>)}</nav><section>
 {tab==="workspace"&&<><article className="panel"><p className="eyebrow">WORKSPACE PROFILE</p><h2>Identity</h2><p className="muted">The workspace identity used throughout AGATA.</p><div className="field"><label>Workspace name</label><input value={name} onChange={e=>setName(e.target.value)}/></div><div className="field"><label>Workspace ID</label><input readOnly value={data?.company?.id||""}/></div><button className="save" onClick={save}>Save changes</button>{saved&&<p className="muted">{saved}</p>}</article><article className="panel"><p className="eyebrow">WORKSPACE PRINCIPLES</p><div className="switch"><div><strong>Evidence before opinion</strong><div className="muted">Readiness decisions remain grounded in recorded evidence.</div></div><span>ON</span></div><div className="switch"><div><strong>Rumi uses workspace context</strong><div className="muted">AI assistance should explain available workspace data rather than invent status.</div></div><span>ON</span></div></article></>}
 {tab==="account"&&<article className="panel"><p className="eyebrow">YOUR ACCOUNT</p><h2>{data?.user?.name||"Account"}</h2><p className="muted">{data?.user?.email||""}</p><div className="field"><label>Account ID</label><input readOnly value={data?.user?.id||""}/></div></article>}
 {tab==="notifications"&&<article className="panel"><p className="eyebrow">NOTIFICATION POLICY</p><h2>Attention signals</h2><p className="muted">AGATA currently generates workspace notifications from readiness, evidence expiration and evidence-mapping conditions. Use the Notifications area to triage them.</p></article>}
 {tab==="intelligence"&&<article className="panel"><p className="eyebrow">RUMI INTELLIGENCE</p><h2>Grounded assistance</h2><p className="muted">Rumi is connected to AGATA's workspace context. Deterministic readiness calculations remain the source of truth; Rumi explains and navigates that information.</p></article>}
 {tab==="security"&&<article className="panel"><p className="eyebrow">SECURITY</p><h2>Account protection</h2><p className="muted">Authentication is handled by the AGATA API. Session and credential management can be expanded here as the workspace moves toward production identity infrastructure.</p></article>}
 </section></div></main>;
}
