import { useEffect, useState } from "react";
import { api } from "../lib/api";

type Member={id:string;name:string;email:string;joined_at:string;status:string;role:string;role_name:string};
type Invite={id:string;email:string;role:string;status:string;created_at:string;expires_at?:string|null;accepted_at?:string|null};
type Role={key:string;name:string;description:string;is_system:boolean};
type Access={role:string;role_name:string;status:string;permissions:string[]};

const css=`.team-page{max-width:1180px;margin:0 auto;padding:32px;color:#eef2f7}.team-head{display:flex;justify-content:space-between;gap:20px;align-items:end}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d}.team-head h1{margin:8px 0}.muted{color:#8792a3}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;margin-top:20px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;padding:16px;border-bottom:1px solid rgba(255,255,255,.07)}input,select{background:#0e1117;color:#eef2f7;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:11px 12px}.btn{background:#e8edf5;color:#080a0e;border:0;border-radius:10px;padding:10px 13px;font-weight:700;cursor:pointer}.btn:disabled{opacity:.5;cursor:not-allowed}.member{display:flex;align-items:center;gap:14px;padding:17px 20px;border-bottom:1px solid rgba(255,255,255,.06)}.avatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#151a23;font-weight:800}.member-main{flex:1}.role{font-size:12px;color:#aab5c5;text-transform:uppercase;letter-spacing:1px}.invite{display:grid;grid-template-columns:1fr 190px auto;gap:10px;width:100%}.actions{display:flex;align-items:center;gap:8px}.access-note{font-size:11px;color:#718094;text-transform:uppercase;letter-spacing:.8px}.role-select{min-width:170px}.status-suspended{color:#e5a7a7}.role-card{padding:14px 18px;border-bottom:1px solid rgba(255,255,255,.06)}.role-card:last-child{border-bottom:0}.role-card strong{display:block}.role-card span{font-size:12px;color:#7f8b9d}.invite-meta{font-size:11px;color:#718094;margin-top:4px}@media(max-width:850px){.member{align-items:flex-start;flex-wrap:wrap}.member-main{min-width:220px}.actions{width:100%;padding-left:54px}.invite{grid-template-columns:1fr}.team-head{align-items:flex-start;flex-direction:column}}`;

const ROLE_KEYS=["member","reviewer","project_manager","compliance_manager","admin"];

export default function TeamPage(){
 const [members,setMembers]=useState<Member[]>([]); const [invites,setInvites]=useState<Invite[]>([]); const [roles,setRoles]=useState<Role[]>([]); const [access,setAccess]=useState<Access|null>(null);
 const [email,setEmail]=useState(""); const [role,setRole]=useState("member"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false); const [busyMember,setBusyMember]=useState("");
 const canInvite=!!access?.permissions.includes("team.invite"); const canManage=!!access?.permissions.includes("team.manage");
 const load=()=>{setError("");return Promise.all([api<Member[]>("/api/workspace/team"),api<Invite[]>("/api/workspace/invitations"),api<Role[]>("/api/workspace/roles"),api<Access>("/api/workspace/access")]).then(([m,i,r,a])=>{setMembers(m);setInvites(i);setRoles(r);setAccess(a);setError("")}).catch(e=>{setError(e instanceof Error?e.message:"Unable to load workspace access.");throw e;});};
 useEffect(()=>{load().catch(()=>undefined)},[]);
 async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/workspace/invitations",{method:"POST",body:JSON.stringify({email,role})});setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to send invitation.")}finally{setBusy(false)}}
 async function resend(id:string){setBusyMember(id);setError("");try{await api(`/api/workspace/invitations/${id}/resend`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to resend invitation.")}finally{setBusyMember("")}}
 async function revoke(id:string){setBusyMember(id);setError("");try{await api(`/api/workspace/invitations/${id}/revoke`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to revoke invitation.")}finally{setBusyMember("")}}
 async function changeRole(id:string,newRole:string){setBusyMember(id);setError("");try{await api(`/api/workspace/team/${id}/role`,{method:"PATCH",body:JSON.stringify({role:newRole})});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to change member role.")}finally{setBusyMember("")}}
 async function changeStatus(member:Member){setBusyMember(member.id);setError("");try{await api(`/api/workspace/team/${member.id}/${member.status==="suspended"?"restore":"suspend"}`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to update member access.")}finally{setBusyMember("")}}
 return <main className="team-page"><style>{css}</style><header className="team-head"><div><p className="eyebrow">WORKSPACE ACCESS</p><h1>Team</h1><p className="muted">Manage people, roles, and access for this workspace.</p></div>{access&&<div><span className="access-note">YOUR ACCESS · {access.role_name}</span></div>}</header>{error&&<div className="panel" style={{padding:16}}>{error}</div>}
 {canInvite?<section className="panel"><div className="toolbar"><div style={{flex:1}}><strong>Invite someone</strong><div className="muted" style={{fontSize:13,marginTop:3}}>AGATA creates a time-limited invitation and sends it through the configured email provider. In development without a provider key, the invitation link is printed by the backend.</div></div><form className="invite" onSubmit={invite}><input type="email" required placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}>{ROLE_KEYS.map(key=><option key={key} value={key}>{roles.find(r=>r.key===key)?.name||key}</option>)}</select><button className="btn" disabled={busy}>{busy?"Sending…":"Invite"}</button></form></div></section>:<section className="panel" style={{padding:18}}><strong>Invitation management is restricted</strong><div className="muted" style={{fontSize:13,marginTop:4}}>Your current workspace role does not have permission to invite people.</div></section>}
 <section className="panel"><div style={{padding:18,borderBottom:"1px solid rgba(255,255,255,.07)"}}><p className="eyebrow">ACTIVE MEMBERS · {members.length}</p></div>{members.map(m=><div className="member" key={m.id}><div className="avatar">{m.name?.[0]?.toUpperCase()||"A"}</div><div className="member-main"><strong>{m.name}</strong><div className="muted" style={{fontSize:13,marginTop:3}}>{m.email}</div></div><span className={m.status==="suspended"?"access-note status-suspended":"access-note"}>{m.status}</span>{m.role==="owner"?<span className="role">Owner</span>:canManage?<div className="actions"><select className="role-select" value={m.role} disabled={busyMember===m.id} onChange={e=>changeRole(m.id,e.target.value)}>{ROLE_KEYS.map(key=><option key={key} value={key}>{roles.find(r=>r.key===key)?.name||key}</option>)}</select><button className="btn" disabled={busyMember===m.id} onClick={()=>changeStatus(m)}>{m.status==="suspended"?"Restore":"Suspend"}</button></div>:<span className="role">{m.role_name}</span>}</div>)}{!members.length&&<div style={{padding:24}} className="muted">No workspace members found.</div>}</section>
 <section className="panel"><div style={{padding:18,borderBottom:"1px solid rgba(255,255,255,.07)"}}><p className="eyebrow">INVITATIONS · {invites.filter(i=>i.status==="pending").length} PENDING</p></div>{invites.map(i=><div className="member" key={i.id}><div className="member-main"><strong>{i.email}</strong><div className="muted" style={{fontSize:13,marginTop:3}}>{roles.find(r=>r.key===i.role)?.name||i.role} · created {new Date(i.created_at).toLocaleDateString()}</div>{i.expires_at&&i.status==="pending"&&<div className="invite-meta">Expires {new Date(i.expires_at).toLocaleString()}</div>}</div><span className="role">{i.status}</span>{i.status==="pending"&&canManage&&<div className="actions"><button className="btn" disabled={busyMember===i.id} onClick={()=>resend(i.id)}>Resend</button><button className="btn" disabled={busyMember===i.id} onClick={()=>revoke(i.id)}>Revoke</button></div>}</div>)}{!invites.length&&<div style={{padding:24}} className="muted">No invitations yet.</div>}</section>
 <section className="panel"><div style={{padding:18,borderBottom:"1px solid rgba(255,255,255,.07)"}}><p className="eyebrow">ROLE MODEL</p></div>{roles.map(r=><div className="role-card" key={r.key}><strong>{r.name}</strong><span>{r.description}</span></div>)}</section>
 </main>;
}
