import { useEffect, useState } from "react";
import { api } from "../lib/api";

type Member={id:string;name:string;email:string;joined_at:string;status:string;role?:string};
type Invite={id:string;email:string;role:string;status:string;created_at:string};
const css=`.team-page{max-width:1180px;margin:0 auto;padding:32px;color:#eef2f7}.team-head{display:flex;justify-content:space-between;gap:20px;align-items:end}.eyebrow{font-size:11px;letter-spacing:1.8px;color:#7f8b9d}.team-head h1{margin:8px 0}.muted{color:#8792a3}.panel{background:#090b0f;border:1px solid rgba(255,255,255,.08);border-radius:16px;overflow:hidden;margin-top:20px}.toolbar{display:flex;gap:10px;flex-wrap:wrap;padding:16px;border-bottom:1px solid rgba(255,255,255,.07)}input,select{background:#0e1117;color:#eef2f7;border:1px solid rgba(255,255,255,.1);border-radius:10px;padding:11px 12px}.btn{background:#e8edf5;color:#080a0e;border:0;border-radius:10px;padding:11px 15px;font-weight:700;cursor:pointer}.member{display:flex;align-items:center;gap:14px;padding:17px 20px;border-bottom:1px solid rgba(255,255,255,.06)}.avatar{width:40px;height:40px;border-radius:50%;display:grid;place-items:center;background:#151a23;font-weight:800}.member-main{flex:1}.role{font-size:12px;color:#aab5c5;text-transform:uppercase;letter-spacing:1px}.invite{display:grid;grid-template-columns:1fr 140px auto;gap:10px;width:100%}@media(max-width:700px){.invite{grid-template-columns:1fr}.team-head{align-items:flex-start;flex-direction:column}}`;

export default function TeamPage(){
 const [members,setMembers]=useState<Member[]>([]); const [invites,setInvites]=useState<Invite[]>([]); const [email,setEmail]=useState(""); const [role,setRole]=useState("member"); const [error,setError]=useState(""); const [busy,setBusy]=useState(false);
 const load=()=>Promise.all([api<Member[]>("/api/workspace/team"),api<Invite[]>("/api/workspace/invitations")]).then(([m,i])=>{setMembers(m);setInvites(i)}).catch(e=>setError(e instanceof Error?e.message:"Unable to load workspace access."));
 useEffect(()=>{load()},[]);
 async function invite(e:React.FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/workspace/invitations",{method:"POST",body:JSON.stringify({email,role})});setEmail("");await load()}catch(e){setError(e instanceof Error?e.message:"Unable to create invitation.")}finally{setBusy(false)}}
 async function revoke(id:string){try{await api(`/api/workspace/invitations/${id}/revoke`,{method:"POST"});await load()}catch(e){setError(e instanceof Error?e.message:"Unable to revoke invitation.")}}
 return <main className="team-page"><style>{css}</style><header className="team-head"><div><p className="eyebrow">WORKSPACE ACCESS</p><h1>Team</h1><p className="muted">Manage people and invitations for this workspace.</p></div></header>{error&&<div className="panel" style={{padding:16}}>{error}</div>}
 <section className="panel"><div className="toolbar"><div style={{flex:1}}><strong>Invite someone</strong><div className="muted" style={{fontSize:13,marginTop:3}}>Invitations are recorded in AGATA; delivery can be connected to your email provider.</div></div><form className="invite" onSubmit={invite}><input type="email" required placeholder="name@company.com" value={email} onChange={e=>setEmail(e.target.value)}/><select value={role} onChange={e=>setRole(e.target.value)}><option value="member">Member</option><option value="admin">Admin</option></select><button className="btn" disabled={busy}>{busy?"Sending…":"Invite"}</button></form></div></section>
 <section className="panel"><div style={{padding:18,borderBottom:"1px solid rgba(255,255,255,.07)"}}><p className="eyebrow">ACTIVE MEMBERS · {members.length}</p></div>{members.map(m=><div className="member" key={m.id}><div className="avatar">{m.name?.[0]?.toUpperCase()||"A"}</div><div className="member-main"><strong>{m.name}</strong><div className="muted" style={{fontSize:13,marginTop:3}}>{m.email}</div></div><span className="role">{m.role||"Member"}</span><span className="muted" style={{fontSize:12}}>{m.status}</span></div>)}{!members.length&&<div style={{padding:24}} className="muted">No workspace members found.</div>}</section>
 <section className="panel"><div style={{padding:18,borderBottom:"1px solid rgba(255,255,255,.07)"}}><p className="eyebrow">INVITATIONS · {invites.filter(i=>i.status==="pending").length} PENDING</p></div>{invites.map(i=><div className="member" key={i.id}><div className="member-main"><strong>{i.email}</strong><div className="muted" style={{fontSize:13,marginTop:3}}>{i.role} · {new Date(i.created_at).toLocaleDateString()}</div></div><span className="role">{i.status}</span>{i.status==="pending"&&<button className="btn" onClick={()=>revoke(i.id)}>Revoke</button>}</div>)}{!invites.length&&<div style={{padding:24}} className="muted">No invitations yet.</div>}</section>
 </main>;
}
